language: python

python:
    - "3.5"
    - "3.6"

before_install:
  - mkdir -p $HOME/.config/matplotlib

install:
  - pip install -r requirements.txt

cache:
  directories:
    - $HOME/.cache/matplotlib

script:
  python setup.py test

