language: python

python:
    - "3.5"
    - "3.6"

before_install:
  - mkdir -p $HOME/.config/matplotlib

install:
  - pip install -r requirements.txt
  - pip install .

cache:
  directories:
    - $HOME/.cache/matplotlib


before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - python -c 'import matplotlib;matplotlib.use('Agg');import matplotlib.pyplot'

script:
  pytest

